### ISSUE TITLE
Deadlock while working with the DeviceUnit and DalUnit registries

### ISSUE THREAD

**Issue by pLeminoq** [openbase/bco.registry#13]
<pre>"pool-1-thread-100":
	at sun.misc.Unsafe.park(Native Method)
	- parking to wait for  <0x0000000084895b00> (a java.util.concurrent.locks.ReentrantReadWriteLock$NonfairSync)
	at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.parkAndCheckInterrupt(AbstractQueuedSynchronizer.java:836)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.doAcquireShared(AbstractQueuedSynchronizer.java:967)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireShared(AbstractQueuedSynchronizer.java:1283)
	at java.util.concurrent.locks.ReentrantReadWriteLock$ReadLock.lock(ReentrantReadWriteLock.java:727)
	at org.openbase.jul.storage.registry.AbstractRegistry.isEmpty(AbstractRegistry.java:366)
	at org.openbase.jul.storage.registry.AbstractRegistry.checkConsistency(AbstractRegistry.java:631)
	at org.openbase.jul.storage.registry.AbstractRegistry$DependencyConsistencyCheckTrigger.update(AbstractRegistry.java:1038)
	at org.openbase.jul.pattern.ObservableImpl.notifyObservers(ObservableImpl.java:163)
	- locked <0x000000008489c580> (a java.lang.Object)
	at org.openbase.jul.pattern.AbstractObservable.notifyObservers(AbstractObservable.java:136)
	at org.openbase.jul.storage.registry.AbstractRegistry.notifyObservers(AbstractRegistry.java:578)
	at org.openbase.jul.storage.registry.AbstractRegistry.update(AbstractRegistry.java:228)
	at org.openbase.jul.storage.registry.FileSynchronizedRegistryImpl.update(FileSynchronizedRegistryImpl.java:153)
	at org.openbase.jul.storage.registry.ProtoBufFileSynchronizedRegistry.update(ProtoBufFileSynchronizedRegistry.java:150)
	at org.openbase.bco.registry.unit.core.UnitRegistryController.lambda$updateUnitConfig$2(UnitRegistryController.java:505)
	at org.openbase.bco.registry.unit.core.UnitRegistryController$$Lambda$42/1726972412.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
"pool-1-thread-85":
	at org.openbase.jul.pattern.ObservableImpl.notifyObservers(ObservableImpl.java:147)
	- waiting to lock <0x000000008489c580> (a java.lang.Object)
	at org.openbase.jul.pattern.AbstractObservable.notifyObservers(AbstractObservable.java:136)
	at org.openbase.jul.storage.registry.AbstractRegistry.notifyObservers(AbstractRegistry.java:578)
	at org.openbase.jul.storage.registry.AbstractRegistry.register(AbstractRegistry.java:169)
	at org.openbase.jul.storage.registry.FileSynchronizedRegistryImpl.register(FileSynchronizedRegistryImpl.java:143)
	at org.openbase.jul.storage.registry.ProtoBufFileSynchronizedRegistry.register(ProtoBufFileSynchronizedRegistry.java:139)
	at org.openbase.bco.registry.unit.core.plugin.DeviceConfigDeviceClassUnitConsistencyPlugin.updateUnitConfigs(DeviceConfigDeviceClassUnitConsistencyPlugin.java:123)
	at org.openbase.bco.registry.unit.core.plugin.DeviceConfigDeviceClassUnitConsistencyPlugin.afterConsistencyCheck(DeviceConfigDeviceClassUnitConsistencyPlugin.java:69)
	at org.openbase.jul.storage.registry.plugin.RegistryPluginPool.afterConsistencyCheck(RegistryPluginPool.java:323)
	at org.openbase.jul.storage.registry.AbstractRegistry.afterConsistencyCheck(AbstractRegistry.java:782)
	at org.openbase.jul.storage.registry.FileSynchronizedRegistryImpl.afterConsistencyCheck(FileSynchronizedRegistryImpl.java:192)
	at org.openbase.jul.storage.registry.AbstractRegistry.checkConsistency(AbstractRegistry.java:768)
	at org.openbase.jul.storage.registry.AbstractRegistry.finishTransaction(AbstractRegistry.java:787)
	at org.openbase.jul.storage.registry.AbstractRegistry.register(AbstractRegistry.java:159)
	at org.openbase.jul.storage.registry.FileSynchronizedRegistryImpl.register(FileSynchronizedRegistryImpl.java:143)
	at org.openbase.jul.storage.registry.ProtoBufFileSynchronizedRegistry.register(ProtoBufFileSynchronizedRegistry.java:139)
	at org.openbase.bco.registry.unit.core.UnitRegistryController.lambda$registerUnitConfig$1(UnitRegistryController.java:471)
	at org.openbase.bco.registry.unit.core.UnitRegistryController$$Lambda$41/900211602.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
</pre>

**Comment by pLeminoq** [comment]
This deadlock problem should be fixed after openbase/jul@06c241a900d5f7f70baefd2f213ba8fd15467325
