### ISSUE TITLE
The new JPRSBPort property does not work for the registry

### ISSUE THREAD

**Issue by pLeminoq** [openbase/bco.registry#24]
When starting the bco-registry launcher or just the unit-registry with the property <em>--rsb-port 4814</em> both components recognize the property but won't use it. The result is the following exception:

<pre>
Mar 07, 2017 10:56:41 AM rsb.transport.spread.SpreadWrapperImpl makeConnection
WARNING: reoccuring SpreadException during connect to daemon
spread.SpreadException: Socket(): java.net.ConnectException: Connection refused (Connection refused)
	at spread.SpreadConnection.connect(SpreadConnection.java:876)
	at rsb.transport.spread.SpreadWrapperImpl.makeConnection(SpreadWrapperImpl.java:145)
	at rsb.transport.spread.SpreadWrapperImpl.activate(SpreadWrapperImpl.java:249)
	at rsb.transport.spread.SpreadReceiver$StateInactive.activate(SpreadReceiver.java:232)
	at rsb.transport.spread.SpreadReceiver.activate(SpreadReceiver.java:344)
	at rsb.transport.spread.SpreadMultiReceiver.subscribe(SpreadMultiReceiver.java:246)
	at rsb.transport.spread.MultiSpreadInPushConnector.activate(MultiSpreadInPushConnector.java:112)
	at rsb.eventprocessing.RouteConfiguratorUtility.activate(RouteConfiguratorUtility.java:90)
	at rsb.eventprocessing.DefaultPushInRouteConfigurator.activate(DefaultPushInRouteConfigurator.java:67)
	at rsb.Listener$StateInactive.activate(Listener.java:122)
	at rsb.Listener.activate(Listener.java:190)
	at org.openbase.jul.extension.rsb.com.RSBSynchronizedParticipant.activate(RSBSynchronizedParticipant.java:167)
	at org.openbase.jul.schedule.WatchDog$Minder.run(WatchDog.java:247)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

10:56:41.889 [pool-2-thread-1] ERROR o.o.j.s.WatchDog ═╦═⚀ Could not start Service[RSBListener[/registry/unit/status/] 1979046642]!
10:56:41.890 [pool-2-thread-1] ERROR o.o.j.s.WatchDog  ╚══╦═⚀ Could not activate listener!
10:56:41.890 [pool-2-thread-1] ERROR o.o.j.s.WatchDog     ╚══╦═⚀ Could not create spread connection host=localhost, port=4803
10:56:41.890 [pool-2-thread-1] ERROR o.o.j.s.WatchDog        ╚════⚀ Socket(): java.net.ConnectException: Connection refused (Connection refused)
</pre>

It clearly shows that the default port 4803 is used but not the given one.
Yet when registering the same property for the registry-editor and starting it the same way I didn't encounter this problem.

**Comment by pLeminoq** [comment]
Fixed by openbase/jul@333d90bec795843344e9f18f246bb5341e16f25e.

The problem was that the AbstractLauncher is an RSBCommunicationService and therefore the SharedParticpantConfig was loaded before the registration of the JPProperties.
