### ISSUE TITLE
Fix DalRegisterDeviceTest.testRegisterDeviceWhileRunning test failures.

### ISSUE THREAD

**Issue by DivineThreepwood** [openbase/bco.registry#53]
In this test sometimes the units of the device are not initialized but activated:

<pre>
22:35:30.202 [Thread-11495] INFO  o.o.b.m.d.c.DeviceManagerController$1 1 registry changes applied. 1 is skipped.
22:35:30.202 [Thread-11495] ERROR o.o.b.m.d.c.DeviceManagerController$1 ═╦═⚀ Entry registry sync failed!
22:35:30.202 [Thread-11495] ERROR o.o.b.m.d.c.DeviceManagerController$1  ╚══╦═⚄ Could not sync all entries!
22:35:30.202 [Thread-11495] ERROR o.o.b.m.d.c.DeviceManagerController$1     ╚══╦═⚄ Could not register 1 entries!
22:35:30.202 [Thread-11495] ERROR o.o.b.m.d.c.DeviceManagerController$1        ╚══╦═⚄ Could not activate all hosted units of GenericDeviceController[DEVICE[RunningDevice]]
22:35:30.202 [Thread-11495] ERROR o.o.b.m.d.c.DeviceManagerController$1           ╚════⚀ communication service is not initialized yet!
22:35:30.202 [Thread-11495] ERROR o.o.b.m.d.c.DeviceManagerController$1 =====================================
22:35:30.347 [Thread-11495] ERROR o.o.b.m.d.c.DeviceManagerController$1 Entry registry sync failed!
org.openbase.jul.exception.CouldNotPerformException: Entry registry sync failed!
	at org.openbase.jul.storage.registry.RegistrySynchronizer.internalSync(RegistrySynchronizer.java:238)
	at org.openbase.jul.storage.registry.RegistrySynchronizer.access$000(RegistrySynchronizer.java:55)
	at org.openbase.jul.storage.registry.RegistrySynchronizer$1.relay(RegistrySynchronizer.java:86)
	at org.openbase.jul.schedule.RecurrenceEventFilter.callRelay(RecurrenceEventFilter.java:113)
	at org.openbase.jul.schedule.RecurrenceEventFilter.trigger(RecurrenceEventFilter.java:96)
	at org.openbase.jul.storage.registry.RegistrySynchronizer.lambda$new$0(RegistrySynchronizer.java:95)
	at org.openbase.jul.pattern.AbstractObservable.notifyObservers(AbstractObservable.java:244)
	at org.openbase.jul.pattern.AbstractObservable.notifyObservers(AbstractObservable.java:188)
	at org.openbase.jul.storage.registry.AbstractRegistry.notifyObservers(AbstractRegistry.java:662)
	at org.openbase.jul.storage.registry.AbstractRegistry.replaceInternalMap(AbstractRegistry.java:529)
	at org.openbase.jul.storage.registry.AbstractRegistry.replaceInternalMap(AbstractRegistry.java:496)
	at org.openbase.jul.storage.registry.RemoteRegistry.notifyRegistryUpdate(RemoteRegistry.java:75)
	at org.openbase.bco.registry.lib.com.SynchronizedRemoteRegistry$RemoteRegistrySynchronizer.update(SynchronizedRemoteRegistry.java:194)
	at org.openbase.bco.registry.lib.com.SynchronizedRemoteRegistry$RemoteRegistrySynchronizer.update(SynchronizedRemoteRegistry.java:178)
	at org.openbase.jul.pattern.AbstractObservable.notifyObservers(AbstractObservable.java:244)
	at org.openbase.jul.pattern.AbstractObservable.notifyObservers(AbstractObservable.java:188)
	at org.openbase.jul.extension.rsb.com.RSBRemoteService.applyDataUpdate(RSBRemoteService.java:1156)
	at org.openbase.jul.extension.rsb.com.RSBRemoteService.access$900(RSBRemoteService.java:72)
	at org.openbase.jul.extension.rsb.com.RSBRemoteService$InternalUpdateHandler.internalNotify(RSBRemoteService.java:1091)
	at rsb.eventprocessing.SingleThreadEventReceivingStrategy$DispatchThread.run(SingleThreadEventReceivingStrategy.java:92)
Caused by: org.openbase.jul.exception.MultiException: Could not sync all entries!
	at org.openbase.jul.exception.MultiException.checkAndThrow(MultiException.java:62)
	at org.openbase.jul.storage.registry.RegistrySynchronizer.internalSync(RegistrySynchronizer.java:236)
	... 19 common frames omitted
Caused by: org.openbase.jul.exception.MultiException: Could not register 1 entries!
	at org.openbase.jul.exception.MultiException.checkAndThrow(MultiException.java:62)
	at org.openbase.jul.storage.registry.RegistrySynchronizer.internalSync(RegistrySynchronizer.java:232)
	... 19 common frames omitted
Caused by: org.openbase.jul.exception.MultiException: Could not activate all hosted units of GenericDeviceController[DEVICE[RunningDevice]]
	at org.openbase.jul.exception.MultiException.checkAndThrow(MultiException.java:62)
	at org.openbase.bco.dal.lib.layer.unit.AbstractHostUnitController.activate(AbstractHostUnitController.java:110)
	at org.openbase.jul.storage.registry.ActivatableEntryRegistrySynchronizer.register(ActivatableEntryRegistrySynchronizer.java:61)
	at org.openbase.jul.storage.registry.RegistrySynchronizer.internalSync(RegistrySynchronizer.java:180)
	... 19 common frames omitted
Caused by: org.openbase.jul.exception.NotInitializedException: communication service is not initialized yet!
	at org.openbase.jul.extension.rsb.com.RSBCommunicationService.validateInitialization(RSBCommunicationService.java:755)
	at org.openbase.jul.extension.rsb.com.RSBCommunicationService.activate(RSBCommunicationService.java:328)
	at org.openbase.bco.dal.lib.layer.unit.AbstractHostUnitController.activate(AbstractHostUnitController.java:104)
	... 21 common frames omitted
22:35:30.347 [Thread-11495] ERROR o.o.b.m.d.c.DeviceManagerController$1 =====================================
Exception in thread "Thread-11495" java.lang.AssertionError
	at org.openbase.jul.storage.registry.RegistrySynchronizer.internalSync(RegistrySynchronizer.java:241)
	at org.openbase.jul.storage.registry.RegistrySynchronizer.access$000(RegistrySynchronizer.java:55)
	at org.openbase.jul.storage.registry.RegistrySynchronizer$1.relay(RegistrySynchronizer.java:86)
	at org.openbase.jul.schedule.RecurrenceEventFilter.callRelay(RecurrenceEventFilter.java:113)
	at org.openbase.jul.schedule.RecurrenceEventFilter.trigger(RecurrenceEventFilter.java:96)
	at org.openbase.jul.storage.registry.RegistrySynchronizer.lambda$new$0(RegistrySynchronizer.java:95)
	at org.openbase.jul.pattern.AbstractObservable.notifyObservers(AbstractObservable.java:244)
	at org.openbase.jul.pattern.AbstractObservable.notifyObservers(AbstractObservable.java:188)
	at org.openbase.jul.storage.registry.AbstractRegistry.notifyObservers(AbstractRegistry.java:662)
	at org.openbase.jul.storage.registry.AbstractRegistry.replaceInternalMap(AbstractRegistry.java:529)
	at org.openbase.jul.storage.registry.AbstractRegistry.replaceInternalMap(AbstractRegistry.java:496)
	at org.openbase.jul.storage.registry.RemoteRegistry.notifyRegistryUpdate(RemoteRegistry.java:75)
	at org.openbase.bco.registry.lib.com.SynchronizedRemoteRegistry$RemoteRegistrySynchronizer.update(SynchronizedRemoteRegistry.java:194)
	at org.openbase.bco.registry.lib.com.SynchronizedRemoteRegistry$RemoteRegistrySynchronizer.update(SynchronizedRemoteRegistry.java:178)
	at org.openbase.jul.pattern.AbstractObservable.notifyObservers(AbstractObservable.java:244)
	at org.openbase.jul.pattern.AbstractObservable.notifyObservers(AbstractObservable.java:188)
	at org.openbase.jul.extension.rsb.com.RSBRemoteService.applyDataUpdate(RSBRemoteService.java:1156)
	at org.openbase.jul.extension.rsb.com.RSBRemoteService.access$900(RSBRemoteService.java:72)
	at org.openbase.jul.extension.rsb.com.RSBRemoteService$InternalUpdateHandler.internalNotify(RSBRemoteService.java:1091)
	at rsb.eventprocessing.SingleThreadEventReceivingStrategy$DispatchThread.run(SingleThreadEventReceivingStrategy.java:92)
</pre>

**Comment by pLeminoq** [comment]
More logging is needed. I cannot reproduce this bug. Is this still happening?

**Comment by TimoMichi** [comment]
<pre>
testRegisterDeviceWhileRunning
18:09:27.362 [pool-1-thread-93] INFO  o.o.j.s.r.ProtoBufFileSynchronizedRegistry Register DeviceClass[TestRegisterDeviceWhileRunnint]...
18:09:27.363 [pool-1-thread-93] INFO  o.o.j.s.r.ProtoBufFileSynchronizedRegistry 3% of max consistency checks passed of DeviceClassRegistry after 1 applied modifications.
18:09:27.364 [pool-1-thread-93] INFO  o.o.j.s.r.ProtoBufFileSynchronizedRegistry 100% consistency checks passed of DeviceClassRegistry after 2 applied modifications.
18:09:27.372 [Thread-3822] INFO  o.o.b.d.r.u.MotionDetectorRemote Connection reestablished MotionDetectorRemote[scope:/paradise/motiondetector/motion_sensor_unit_test/]
18:09:27.373 [Thread-1914] INFO  o.o.b.d.r.u.RollerShutterRemote Connection reestablished RollerShutterRemote[scope:/paradise/rollershutter/rollershutter_unit_test/]
18:09:27.378 [pool-1-thread-93] INFO  o.o.j.s.r.ProtoBufFileSynchronizedRegistry Register UnitConfig[RunningDevice]...
18:09:27.379 [Thread-1293] INFO  o.o.b.d.r.u.TamperDetectorRemote Connection reestablished TamperDetectorRemote[scope:/paradise/tamperdetector/tamper_switch_unit_test/]
18:09:27.380 [pool-1-thread-93] INFO  o.o.j.s.r.ProtoBufFileSynchronizedRegistry 0% of max consistency checks passed of DeviceConfigRegistry after 1 applied modifications.
18:09:27.381 [pool-1-thread-93] INFO  o.o.j.s.r.ProtoBufFileSynchronizedRegistry 100% consistency checks passed of DeviceConfigRegistry after 5 applied modifications.
18:09:27.382 [pool-1-thread-93] INFO  o.o.j.s.r.ProtoBufFileSynchronizedRegistry Register UnitConfig[603da23d-a748-43e5-aef5-6d036040ce7e]...
18:09:27.383 [Thread-8971] INFO  o.o.b.d.r.u.TemperatureSensorRemote Connection reestablished TemperatureSensorRemote[scope:/paradise/temperaturesensor/temperature_sensor_unit_test/]
18:09:27.385 [Thread-7705] INFO  o.o.b.d.r.u.LightSensorRemote Connection reestablished LightSensorRemote[scope:/paradise/lightsensor/light_sensor_unit_test/]
18:09:27.386 [Thread-8330] INFO  o.o.b.d.r.u.BatteryRemote Connection reestablished BatteryRemote[scope:/paradise/battery/battery_unit_test/]
18:09:27.407 [Thread-11568] INFO  o.o.b.d.r.u.ColorableLightRemote Connection reestablished ColorableLightRemote[scope:/paradise/colorablelight/colorable_light_unit_test/]
18:09:27.408 [Thread-7054] INFO  o.o.b.d.r.u.ColorableLightRemote Connection reestablished ColorableLightRemote[scope:/paradise/colorablelight/colorable_light_unit_test/]
18:09:27.408 [pool-1-thread-93] INFO  o.o.j.s.r.ProtoBufFileSynchronizedRegistry 0% of max consistency checks passed of DalUnitConfigRegistry after 1 applied modifications.
18:09:27.420 [Thread-9625] INFO  o.o.b.d.r.u.ReedContactRemote Connection reestablished ReedContactRemote[scope:/paradise/reedcontact/reed_switch_unit_test/]
18:09:27.423 [Thread-4474] INFO  o.o.b.d.r.u.PowerConsumptionSensorRemote Connection reestablished PowerConsumptionSensorRemote[scope:/paradise/powerconsumptionsensor/power_consumption_sensor_unit_test/]
18:09:27.429 [Thread-11575] INFO  o.o.b.d.r.u.PowerSwitchRemote Connection reestablished PowerSwitchRemote[scope:/paradise/powerswitch/power_plug_unit_test/]
18:09:27.430 [Thread-2566] INFO  o.o.b.d.r.u.PowerSwitchRemote Connection reestablished PowerSwitchRemote[scope:/paradise/powerswitch/power_plug_unit_test/]
18:09:27.434 [pool-1-thread-93] INFO  o.o.j.s.r.ProtoBufFileSynchronizedRegistry 100% consistency checks passed of DalUnitConfigRegistry after 12 applied modifications.
18:09:27.436 [Thread-11574] INFO  o.o.b.d.r.u.ColorableLightRemote Connection reestablished ColorableLightRemote[scope:/paradise/stairway_to_heaven/colorablelight/ph_hue_e27_device_heaven/]
18:09:27.441 [Thread-11563] INFO  o.o.b.d.r.u.DimmerRemote Connection reestablished DimmerRemote[scope:/paradise/dimmer/dimmer_unit_test/]
18:09:27.453 [Thread-11565] INFO  o.o.b.d.r.u.LightRemote Connection reestablished LightRemote[scope:/paradise/light/light_unit_test/]
18:09:27.453 [Thread-10921] INFO  o.o.b.d.r.u.LightRemote Connection reestablished LightRemote[scope:/paradise/light/light_unit_test/]
18:09:27.463 [Thread-6399] INFO  o.o.b.d.r.u.ButtonRemote Connection reestablished ButtonRemote[scope:/paradise/button/button_unit_test/]
18:09:27.466 [pool-1-thread-93] INFO  o.o.j.s.r.ProtoBufFileSynchronizedRegistry 1% of max consistency checks passed of LocationConfigRegistry after 1 applied modifications.
18:09:27.467 [pool-1-thread-93] INFO  o.o.j.s.r.ProtoBufFileSynchronizedRegistry 100% consistency checks passed of LocationConfigRegistry after 1 applied modifications.
18:09:27.467 [pool-1-thread-93] INFO  o.o.j.s.r.ProtoBufFileSynchronizedRegistry Update UnitConfig[RunningDevice]...
18:09:27.470 [Thread-11566] INFO  o.o.b.d.r.u.ColorableLightRemote Connection reestablished ColorableLightRemote[scope:/paradise/stairway_to_heaven/colorablelight/ph_hue_e27_device_hell/]
18:09:27.483 [Thread-11553] INFO  o.o.b.d.r.u.ColorableLightRemote Connection reestablished ColorableLightRemote[scope:/paradise/stairway_to_heaven/colorablelight/ph_hue_e27_device_stairway/]
18:09:27.484 [Thread-5125] INFO  o.o.b.d.r.u.HandleRemote Connection reestablished HandleRemote[scope:/paradise/handle/handle_sensor_unit_test/]
18:09:27.486 [Thread-5783] INFO  o.o.b.d.r.u.SmokeDetectorRemote Connection reestablished SmokeDetectorRemote[scope:/paradise/smokedetector/smoke_detector_unit_test/]
18:09:27.500 [Thread-11567] INFO  o.o.b.d.r.u.DimmableLightRemote Connection reestablished DimmableLightRemote[scope:/paradise/dimmablelight/dimmablelight_unit_test/]
18:09:27.500 [Thread-10277] INFO  o.o.b.d.r.u.DimmableLightRemote Connection reestablished DimmableLightRemote[scope:/paradise/dimmablelight/dimmablelight_unit_test/]
18:09:27.500 [Thread-3194] INFO  o.o.b.d.r.u.TemperatureControllerRemote Connection reestablished TemperatureControllerRemote[scope:/paradise/temperaturecontroller/temperature_controller_unit_test/]
18:09:27.554 [Thread-5783] INFO  o.o.b.d.r.u.SmokeDetectorRemote Remote connection to Controller[/paradise/smokedetector/smoke_detector_unit_test/] was detached because the controller shutdown was initiated.
18:09:27.557 [Thread-1914] INFO  o.o.b.d.r.u.RollerShutterRemote Remote connection to Controller[/paradise/rollershutter/rollershutter_unit_test/] was detached because the controller shutdown was initiated.
18:09:27.566 [Thread-11553] INFO  o.o.b.d.r.u.ColorableLightRemote Remote connection to Controller[/paradise/stairway_to_heaven/colorablelight/ph_hue_e27_device_stairway/] was detached because the controller shutdown was initiated.
18:09:27.574 [Thread-5125] INFO  o.o.b.d.r.u.HandleRemote Remote connection to Controller[/paradise/handle/handle_sensor_unit_test/] was detached because the controller shutdown was initiated.
18:09:27.577 [Thread-10277] INFO  o.o.b.d.r.u.DimmableLightRemote Remote connection to Controller[/paradise/dimmablelight/dimmablelight_unit_test/] was detached because the controller shutdown was initiated.
18:09:27.578 [Thread-11567] INFO  o.o.b.d.r.u.DimmableLightRemote Remote connection to Controller[/paradise/dimmablelight/dimmablelight_unit_test/] was detached because the controller shutdown was initiated.
18:09:27.586 [Thread-11566] INFO  o.o.b.d.r.u.ColorableLightRemote Remote connection to Controller[/paradise/stairway_to_heaven/colorablelight/ph_hue_e27_device_hell/] was detached because the controller shutdown was initiated.
18:09:27.592 [Thread-7054] INFO  o.o.b.d.r.u.ColorableLightRemote Remote connection to Controller[/paradise/colorablelight/colorable_light_unit_test/] was detached because the controller shutdown was initiated.
18:09:27.592 [Thread-11568] INFO  o.o.b.d.r.u.ColorableLightRemote Remote connection to Controller[/paradise/colorablelight/colorable_light_unit_test/] was detached because the controller shutdown was initiated.
18:09:27.604 [Thread-11575] INFO  o.o.b.d.r.u.PowerSwitchRemote Remote connection to Controller[/paradise/powerswitch/power_plug_unit_test/] was detached because the controller shutdown was initiated.
18:09:27.604 [Thread-2566] INFO  o.o.b.d.r.u.PowerSwitchRemote Remote connection to Controller[/paradise/powerswitch/power_plug_unit_test/] was detached because the controller shutdown was initiated.
18:09:27.606 [Thread-4474] INFO  o.o.b.d.r.u.PowerConsumptionSensorRemote Remote connection to Controller[/paradise/powerconsumptionsensor/power_consumption_sensor_unit_test/] was detached because the controller shutdown was initiated.
18:09:27.608 [Thread-6399] INFO  o.o.b.d.r.u.ButtonRemote Remote connection to Controller[/paradise/button/button_unit_test/] was detached because the controller shutdown was initiated.
18:09:27.611 [Thread-11574] INFO  o.o.b.d.r.u.ColorableLightRemote Remote connection to Controller[/paradise/stairway_to_heaven/colorablelight/ph_hue_e27_device_heaven/] was detached because the controller shutdown was initiated.
18:09:27.614 [Thread-8330] INFO  o.o.b.d.r.u.BatteryRemote Remote connection to Controller[/paradise/battery/battery_unit_test/] was detached because the controller shutdown was initiated.
18:09:27.616 [Thread-1293] INFO  o.o.b.d.r.u.TamperDetectorRemote Remote connection to Controller[/paradise/tamperdetector/tamper_switch_unit_test/] was detached because the controller shutdown was initiated.
18:09:27.617 [Thread-8971] INFO  o.o.b.d.r.u.TemperatureSensorRemote Remote connection to Controller[/paradise/temperaturesensor/temperature_sensor_unit_test/] was detached because the controller shutdown was initiated.
18:09:27.619 [Thread-7705] INFO  o.o.b.d.r.u.LightSensorRemote Remote connection to Controller[/paradise/lightsensor/light_sensor_unit_test/] was detached because the controller shutdown was initiated.
18:09:27.620 [Thread-3822] INFO  o.o.b.d.r.u.MotionDetectorRemote Remote connection to Controller[/paradise/motiondetector/motion_sensor_unit_test/] was detached because the controller shutdown was initiated.
18:09:27.624 [Thread-11565] INFO  o.o.b.d.r.u.LightRemote Remote connection to Controller[/paradise/light/light_unit_test/] was detached because the controller shutdown was initiated.
18:09:27.624 [Thread-10921] INFO  o.o.b.d.r.u.LightRemote Remote connection to Controller[/paradise/light/light_unit_test/] was detached because the controller shutdown was initiated.
18:09:27.628 [Thread-3194] INFO  o.o.b.d.r.u.TemperatureControllerRemote Remote connection to Controller[/paradise/temperaturecontroller/temperature_controller_unit_test/] was detached because the controller shutdown was initiated.
18:09:27.633 [Thread-9625] INFO  o.o.b.d.r.u.ReedContactRemote Remote connection to Controller[/paradise/reedcontact/reed_switch_unit_test/] was detached because the controller shutdown was initiated.
18:09:27.636 [Thread-11563] INFO  o.o.b.d.r.u.DimmerRemote Remote connection to Controller[/paradise/dimmer/dimmer_unit_test/] was detached because the controller shutdown was initiated.
18:09:27.665 [Thread-11771] INFO  o.o.b.m.d.c.DeviceManagerController$1 1 registry changes applied. 1 is skipped.
18:09:27.665 [Thread-11771] ERROR o.o.b.m.d.c.DeviceManagerController$1 ═╦═⚀ Entry registry sync failed!
18:09:27.665 [Thread-11771] ERROR o.o.b.m.d.c.DeviceManagerController$1  ╚══╦═⚄ Could not sync all entries!
18:09:27.665 [Thread-11771] ERROR o.o.b.m.d.c.DeviceManagerController$1     ╚══╦═⚄ Could not register 1 entries!
18:09:27.665 [Thread-11771] ERROR o.o.b.m.d.c.DeviceManagerController$1        ╚══╦═⚄ Could not activate all hosted units of GenericDeviceController[DEVICE[RunningDevice]]
18:09:27.665 [Thread-11771] ERROR o.o.b.m.d.c.DeviceManagerController$1           ╚════⚀ communication service is not initialized yet!
18:09:27.665 [Thread-11771] ERROR o.o.b.m.d.c.DeviceManagerController$1 =====================================
18:09:27.668 [Thread-11771] ERROR o.o.b.m.d.c.DeviceManagerController$1 Entry registry sync failed!
org.openbase.jul.exception.CouldNotPerformException: Entry registry sync failed!
	at org.openbase.jul.storage.registry.RegistrySynchronizer.internalSync(RegistrySynchronizer.java:238)
	at org.openbase.jul.storage.registry.RegistrySynchronizer.access$000(RegistrySynchronizer.java:55)
	at org.openbase.jul.storage.registry.RegistrySynchronizer$1.relay(RegistrySynchronizer.java:86)
	at org.openbase.jul.schedule.RecurrenceEventFilter.relay(RecurrenceEventFilter.java:231)
	at org.openbase.jul.schedule.RecurrenceEventFilter.callRelay(RecurrenceEventFilter.java:216)
	at org.openbase.jul.schedule.RecurrenceEventFilter.trigger(RecurrenceEventFilter.java:153)
	at org.openbase.jul.schedule.RecurrenceEventFilter.trigger(RecurrenceEventFilter.java:104)
	at org.openbase.jul.storage.registry.RegistrySynchronizer.lambda$new$0(RegistrySynchronizer.java:95)
	at org.openbase.jul.pattern.AbstractObservable.notifyObservers(AbstractObservable.java:244)
	at org.openbase.jul.pattern.AbstractObservable.notifyObservers(AbstractObservable.java:188)
	at org.openbase.jul.storage.registry.AbstractRegistry.notifyObservers(AbstractRegistry.java:664)
	at org.openbase.jul.storage.registry.AbstractRegistry.replaceInternalMap(AbstractRegistry.java:531)
	at org.openbase.jul.storage.registry.AbstractRegistry.replaceInternalMap(AbstractRegistry.java:498)
	at org.openbase.jul.storage.registry.RemoteRegistry.notifyRegistryUpdate(RemoteRegistry.java:75)
	at org.openbase.bco.registry.lib.com.SynchronizedRemoteRegistry$RemoteRegistrySynchronizer.update(SynchronizedRemoteRegistry.java:194)
	at org.openbase.bco.registry.lib.com.SynchronizedRemoteRegistry$RemoteRegistrySynchronizer.update(SynchronizedRemoteRegistry.java:178)
	at org.openbase.jul.pattern.AbstractObservable.notifyObservers(AbstractObservable.java:244)
	at org.openbase.jul.pattern.AbstractObservable.notifyObservers(AbstractObservable.java:188)
	at org.openbase.jul.extension.rsb.com.RSBRemoteService.applyDataUpdate(RSBRemoteService.java:1219)
	at org.openbase.jul.extension.rsb.com.RSBRemoteService.access$900(RSBRemoteService.java:72)
	at org.openbase.jul.extension.rsb.com.RSBRemoteService$InternalUpdateHandler.internalNotify(RSBRemoteService.java:1154)
	at rsb.eventprocessing.SingleThreadEventReceivingStrategy$DispatchThread.run(SingleThreadEventReceivingStrategy.java:92)
Caused by: org.openbase.jul.exception.MultiException: Could not sync all entries!
	at org.openbase.jul.exception.MultiException.checkAndThrow(MultiException.java:62)
	at org.openbase.jul.storage.registry.RegistrySynchronizer.internalSync(RegistrySynchronizer.java:236)
	... 21 common frames omitted
Caused by: org.openbase.jul.exception.MultiException: Could not register 1 entries!
	at org.openbase.jul.exception.MultiException.checkAndThrow(MultiException.java:62)
	at org.openbase.jul.storage.registry.RegistrySynchronizer.internalSync(RegistrySynchronizer.java:232)
	... 21 common frames omitted
Caused by: org.openbase.jul.exception.MultiException: Could not activate all hosted units of GenericDeviceController[DEVICE[RunningDevice]]
	at org.openbase.jul.exception.MultiException.checkAndThrow(MultiException.java:62)
	at org.openbase.bco.dal.lib.layer.unit.AbstractHostUnitController.activate(AbstractHostUnitController.java:109)
	at org.openbase.jul.storage.registry.ActivatableEntryRegistrySynchronizer.register(ActivatableEntryRegistrySynchronizer.java:61)
	at org.openbase.jul.storage.registry.RegistrySynchronizer.internalSync(RegistrySynchronizer.java:180)
	... 21 common frames omitted
Caused by: org.openbase.jul.exception.NotInitializedException: communication service is not initialized yet!
	at org.openbase.jul.extension.rsb.com.RSBCommunicationService.validateInitialization(RSBCommunicationService.java:756)
	at org.openbase.jul.extension.rsb.com.RSBCommunicationService.activate(RSBCommunicationService.java:328)
	at org.openbase.bco.dal.lib.layer.unit.AbstractHostUnitController.activate(AbstractHostUnitController.java:103)
	... 23 common frames omitted
18:09:27.669 [Thread-11771] ERROR o.o.b.m.d.c.DeviceManagerController$1 =====================================
Exception in thread "Thread-11771" java.lang.AssertionError
	at org.openbase.jul.storage.registry.RegistrySynchronizer.internalSync(RegistrySynchronizer.java:241)
	at org.openbase.jul.storage.registry.RegistrySynchronizer.access$000(RegistrySynchronizer.java:55)
	at org.openbase.jul.storage.registry.RegistrySynchronizer$1.relay(RegistrySynchronizer.java:86)
	at org.openbase.jul.schedule.RecurrenceEventFilter.relay(RecurrenceEventFilter.java:231)
	at org.openbase.jul.schedule.RecurrenceEventFilter.callRelay(RecurrenceEventFilter.java:216)
	at org.openbase.jul.schedule.RecurrenceEventFilter.trigger(RecurrenceEventFilter.java:153)
	at org.openbase.jul.schedule.RecurrenceEventFilter.trigger(RecurrenceEventFilter.java:104)
	at org.openbase.jul.storage.registry.RegistrySynchronizer.lambda$new$0(RegistrySynchronizer.java:95)
	at org.openbase.jul.pattern.AbstractObservable.notifyObservers(AbstractObservable.java:244)
	at org.openbase.jul.pattern.AbstractObservable.notifyObservers(AbstractObservable.java:188)
	at org.openbase.jul.storage.registry.AbstractRegistry.notifyObservers(AbstractRegistry.java:664)
	at org.openbase.jul.storage.registry.AbstractRegistry.replaceInternalMap(AbstractRegistry.java:531)
	at org.openbase.jul.storage.registry.AbstractRegistry.replaceInternalMap(AbstractRegistry.java:498)
	at org.openbase.jul.storage.registry.RemoteRegistry.notifyRegistryUpdate(RemoteRegistry.java:75)
	at org.openbase.bco.registry.lib.com.SynchronizedRemoteRegistry$RemoteRegistrySynchronizer.update(SynchronizedRemoteRegistry.java:194)
	at org.openbase.bco.registry.lib.com.SynchronizedRemoteRegistry$RemoteRegistrySynchronizer.update(SynchronizedRemoteRegistry.java:178)
	at org.openbase.jul.pattern.AbstractObservable.notifyObservers(AbstractObservable.java:244)
	at org.openbase.jul.pattern.AbstractObservable.notifyObservers(AbstractObservable.java:188)
	at org.openbase.jul.extension.rsb.com.RSBRemoteService.applyDataUpdate(RSBRemoteService.java:1219)
	at org.openbase.jul.extension.rsb.com.RSBRemoteService.access$900(RSBRemoteService.java:72)
	at org.openbase.jul.extension.rsb.com.RSBRemoteService$InternalUpdateHandler.internalNotify(RSBRemoteService.java:1154)
	at rsb.eventprocessing.SingleThreadEventReceivingStrategy$DispatchThread.run(SingleThreadEventReceivingStrategy.java:92)

</pre>

**Comment by pLeminoq** [comment]
Does this issue still exists? I know that I considerably enhanced the test but could not reproduce this issue.

**Comment by pLeminoq** [comment]
Closed because not reproducable
