### ISSUE TITLE
Recently travis often fails on starting the MockRegistry with a CancellationException

### ISSUE THREAD

**Issue by pLeminoq** [openbase/bco.registry#59]
This is the print from the ExceptionPrinter:

<pre>
═╦═⚀ Could not instantiate MockRegistry!
 ╚══╦═⚀ Could not reinitialize CachedUnitRegistryRemote!
    ╚════⚀ CancellationException
=====================================
Could not instantiate MockRegistry!
org.openbase.jul.exception.InstantiationException: Could not instantiate MockRegistry!
	at org.openbase.bco.registry.mock.MockRegistry.<init>(MockRegistry.java:451)
	at org.openbase.bco.registry.mock.MockRegistryHolder.newMockRegistry(MockRegistryHolder.java:43)
	at org.openbase.bco.registry.mock.MockRegistryTest.testMockRegistryCreation(MockRegistryTest.java:76)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:298)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:292)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.openbase.jul.exception.CouldNotPerformException: Could not reinitialize CachedUnitRegistryRemote!
	at org.openbase.bco.registry.unit.remote.CachedUnitRegistryRemote.reinitialize(CachedUnitRegistryRemote.java:72)
	at org.openbase.bco.registry.remote.Registries.reinitialize(Registries.java:286)
	at org.openbase.bco.registry.mock.MockRegistry.<init>(MockRegistry.java:400)
	... 14 more
Caused by: java.util.concurrent.CancellationException
	at java.util.concurrent.CompletableFuture.cancel(CompletableFuture.java:2263)
	at org.openbase.jul.extension.rsb.com.RSBRemoteService.skipSyncTasks(RSBRemoteService.java:1338)
	at org.openbase.jul.extension.rsb.com.RSBRemoteService.deactivate(RSBRemoteService.java:412)
	at org.openbase.bco.registry.lib.com.AbstractRegistryRemote.deactivate(AbstractRegistryRemote.java:96)
	at org.openbase.jul.extension.rsb.com.RSBRemoteService.internalInit(RSBRemoteService.java:225)
	at org.openbase.jul.extension.rsb.com.RSBRemoteService.reinit(RSBRemoteService.java:477)
	at org.openbase.jul.extension.rsb.com.RSBRemoteService.reinit(RSBRemoteService.java:456)
	at org.openbase.jul.extension.rsb.com.RSBRemoteService$1.call(RSBRemoteService.java:750)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	... 1 more
=====================================
</pre>

It seems that after the registry remote has been restarted and already waits for its syncTask, another method call notices an invalid state because of the deactivation and cancels the syncTask.

**Comment by pLeminoq** [comment]
Should be fixed by commit openbase/jul@4f0ad630a71fd01f9d4ec8b64d79508489e2792a which also added a unit test for this problem. Now reinit will not cancel sync tasks anymore because the remote service will be activate afterwards and the task can go on.

**Comment by DivineThreepwood** [comment]
Fix confirmed.
