### ISSUE TITLE
Var directory loading bug

### ISSUE THREAD

**Issue by pLeminoq** [openbase/bco.registry#99]
I think this is a JPS problem but it occurs when using the registry so I will post this issue here. For me the registry will currently not start because I do not have a var directory at my prefix. This is the case even though the var directory and db directory can be found at $HOME/.config/bco/var/registry/db.
If I create an empty var directory at the prefix the registry starts fine and also loads the db from the directory specified above.
Here is the error print:
<pre>
10:07:23.970 [main] ERROR o.o.j.s.r.Registry =========================================================================
10:07:23.970 [main] ERROR o.o.j.s.r.Registry = Could not analyse arguments: Could not init registered properties!
10:07:23.970 [main] ERROR o.o.j.s.r.Registry === Could not init registered properties!
10:07:23.970 [main] ERROR o.o.j.s.r.Registry ===== Could not load Property[JPVarDirectory]!
10:07:23.970 [main] ERROR o.o.j.s.r.Registry ======= Property[JPVarDirectory] is not available!
10:07:23.970 [main] ERROR o.o.j.s.r.Registry ========= Could not load JPVarDirectory[Type:Directory|ExistenceHandling:Must|AutoMode:Off]!
10:07:23.970 [main] ERROR o.o.j.s.r.Registry =========== Could not handle Directory[/home/pleminoq/release/var]!
10:07:23.970 [main] ERROR o.o.j.s.r.Registry ============= Directory[/home/pleminoq/release/var] does not exist!
org.openbase.jps.exception.JPServiceException: Could not analyse arguments: Could not init registered properties!
	at org.openbase.jps.core.JPService.parse(JPService.java:249)
	at org.openbase.jps.core.JPService.parseAndExitOnError(JPService.java:168)
	at org.openbase.jul.pattern.launch.AbstractLauncher.main(AbstractLauncher.java:284)
	at org.openbase.bco.registry.launch.RegistryLauncher.main(RegistryLauncher.java:44)
Caused by: org.openbase.jps.exception.JPServiceException: Could not init registered properties!
	at org.openbase.jps.core.JPService.initRegisteredProperties(JPService.java:354)
	at org.openbase.jps.core.JPService.parse(JPService.java:247)
	... 3 more
Caused by: org.openbase.jps.exception.JPServiceException: Could not load Property[JPVarDirectory]!
	at org.openbase.jps.core.JPService.loadAllProperties(JPService.java:573)
	at org.openbase.jps.core.JPService.initRegisteredProperties(JPService.java:351)
	... 4 more
Caused by: org.openbase.jps.exception.JPNotAvailableException: Property[JPVarDirectory] is not available!
	at org.openbase.jps.core.JPService.getProperty(JPService.java:552)
	at org.openbase.jps.core.JPService.loadAllProperties(JPService.java:570)
	... 5 more
Caused by: org.openbase.jps.exception.JPServiceException: Could not load JPVarDirectory[Type:Directory|ExistenceHandling:Must|AutoMode:Off]!
	at org.openbase.jps.core.JPService.loadProperty(JPService.java:438)
	at org.openbase.jps.core.JPService.getProperty(JPService.java:548)
	... 6 more
Caused by: org.openbase.jps.exception.JPValidationException: Could not handle Directory[/home/pleminoq/release/var]!
	at org.openbase.jps.preset.AbstractJPFile.validate(AbstractJPFile.java:88)
	at org.openbase.jps.preset.JPVarDirectory.validate(JPVarDirectory.java:59)
	at org.openbase.jps.core.JPService.loadProperty(JPService.java:436)
	... 7 more
Caused by: java.io.IOException: Directory[/home/pleminoq/release/var] does not exist!
	at org.openbase.jps.tools.FileHandler.handle(FileHandler.java:96)
	at org.openbase.jps.tools.FileHandler.handle(FileHandler.java:68)
	at org.openbase.jps.preset.AbstractJPFile.validate(AbstractJPFile.java:86)
	... 9 more
10:07:23.971 [main] ERROR o.o.j.s.r.Registry =========================================================================
10:07:23.971 [main] INFO  o.o.j.s.r.Registry Exit registry
</pre>

**Comment by DivineThreepwood** [comment]
This issue occurs since the validation pipeline of jps has been fixes. The var folder must exist check has now be removed from the JPVarDirectoryProperty, because bco is checking the existence of the var directory anyway and there is no possible way to auto detect a cache or var directory via the vm. This solves this issue. A patched jps version is released (v3.4.10).
